name: Build and Deploy

on:
  push:
    branches:
      - master
      - develop
      - 'develop/*'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.GIT_TOKEN}}
          submodules: true

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Deploy use SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          source: "./build/libs/gigacoffee-backend.jar"
          target: "/root/gigacoffee/"

      - name: Run Application use SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          script: sh /root/gigacoffee/deploy.sh
          script_stop: true