name: Build and Deploy

on:
  push:
    branches:
      - master
      - develop
      - 'ci/test'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GIT_TOKEN }}
      - name: Build Application
        run: ./gradlew clean build --exclude-task test
      - name: Upload JAR to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          source: ./build/libs/gigacoffee-backend.jar
          target: /root/gigacoffee/gigacoffee-backend.jar
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            chmod +x /root/gigacoffee/deploy.sh |
            sh /root/gigacoffee/deploy.sh